function [fitresult, gof] = sigmoidfitacetalresin(news, newdydx)
%CREATEFIT(NEWS,NEWDYDX)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : news
%      Y Output: newdydx
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Jul-2019 16:58:47


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( news, newdydx );

% Set up fittype and options.
ft = fittype( '(-1/(p+(a*exp(-b*x+s)))+c)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.StartPoint = [0.337719409821377 0.900053846417662 0.369246781120215 0.111202755293787 0.780252068321138];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'newdydx vs. news', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel news
ylabel newdydx
grid on

